import "./modules/flags.js";
import "./modules/game.js";
import "./modules/game_grid.js";
import "./modules/game_over.js";
import "./modules/github.js"
import "./modules/menu.js";
import "./modules/mines.js";
import "./modules/nodes.js";
import "./modules/settings.js";
import "./modules/run.js";